---
driver:
  name: docker
  provision_command: curl -L http://www.chef.io/chef/install.sh | bash

provisioner:
  name: dummy

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7
  - name: debian
  - name: arch
    driver:
      image: base/archlinux
      provision_command:
  - name: unknown
    driver:
      image: ubuntu:12.04
      platform: ubuntu
  - name: dockerfile
    driver:
      username: dockerfile
      password: dockerfile
      dockerfile: test/Dockerfile
      run_command: /sbin/init
  - name: database
    driver:
      image: ubuntu:14.04
      platform: ubuntu
      instance_name: db
      publish_all: true
  - name: linked
    driver:
      image: ubuntu:14.04
      platform: ubuntu
      links: "db:db"
suites:
  - name: default
    excludes: [arch]
  - name: concurrency
  - name: context
    driver:
      build_context: false
  - name: capabilities
    excludes: [arch,unknown,centos-7,centos-6.7,dockerfile]
    driver:
      provision_command:  
      - curl -L http://www.chef.io/chef/install.sh | bash
      - apt-get install -y net-tools 
      username: kitchen
      password: kitchen 
      cap_drop:
      - NET_ADMIN 
     
