<% # Make sure the local copy of the driver is loaded %>
<% lib = File.expand_path('../lib', __FILE__) %>
<% $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib) %>
---
driver:
  name: docker
  provision_command: curl -L https://www.chef.io/chef/install.sh | bash

transport:
  name: docker

provisioner:
  name: dummy

platforms:
- name: amazonlinux-2
- name: ubuntu-16.04
- name: ubuntu-18.04
- name: fedora-latest
  driver:
    provision_command:
    - yum install libxcrypt-compat.x86_64 -y
    - curl -L https://www.chef.io/chef/install.sh | bash
- name: centos-6
- name: centos-7
- name: oraclelinux-6
- name: oraclelinux-7
- name: debian-8
- name: debian-9
# Removing opensuse CI tests temporarily due to an issue with the Chef install script not providing 
# the correct platform name for opensuse resulting in consistent failures for this platform
#- name: opensuse-42.3
#  driver:
#    image: opensuse/leap:42.3
- name: unknown
  driver:
    image: ubuntu:16.04
    platform: ubuntu
- name: dockerfile
  driver:
    username: dockerfile
    password: dockerfile
    dockerfile: test/Dockerfile
    run_command: /sbin/init

suites:
- name: default
  excludes: [arch]
- name: context
  excludes: [arch]
  driver:
    build_context: false
- name: capabilities
  includes: [debian-8,debian-9,ubuntu-16.04,ubuntu-18.04]
  driver:
    provision_command:
    - curl -L https://www.chef.io/chef/install.sh | bash
    - apt-get install -y net-tools
    cap_drop:
    - NET_ADMIN
- name: inspec
  driver:
    provision_command: true
  verifier:
    name: inspec
